version: '3.8'

services:
  # Database Container
  database:
    image: postgres:15-alpine
    container_name: banking_database
    restart: always
    environment:
      POSTGRES_DB: banking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_PORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banking_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d banking_db -p 5433"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: -p 5433

  # Backend Container
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: banking_backend
    restart: on-failure
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: database
      DB_PORT: 5433
      DB_NAME: banking_db
      DB_USER: postgres
      DB_PASSWORD: 1234
      JWT_SECRET: worawut013
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - banking_network

  # Frontend Container
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: banking_frontend
    restart: always
    environment:
      VUE_APP_API_BASE_URL: http://localhost:3001/api
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - banking_network

volumes:
  postgres_data:

networks:
  banking_network:
    driver: bridge